name: Edge Browser Extract and Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Run once daily

jobs:
  download_extract_upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: versions

    - name: Get Edge versions from redirect URL
      id: get-versions
      run: |
        VERSION_EDGE=$(curl -sIL "https://go.microsoft.com/fwlink/?linkid=2069148&platform=Mac&Consent=0&channel=Stable" | grep -i Location | awk -F '/' '{print $NF}' | awk -F'-' '{print $2}' | awk -F'.' '{print $1"."$2"."$3"."$4}')
        echo "VERSION_EDGE=$VERSION_EDGE" >> $GITHUB_ENV

    - name: Check if versions have changed
      id: check-versions
      run: |
        echo "version_changed=false" >> $GITHUB_OUTPUT
        if [[ -f "previous_version" && $(cat previous_version) != "${VERSION_EDGE}" ]]; then
          echo "${VERSION_EDGE}" > previous_version
          echo "version_changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Download and Extract Edge Browsers
      if: steps.check-versions.outputs.version_changed == 'true'
      run: |
        curl -L -o edge-intel.pkg "https://go.microsoft.com/fwlink/?linkid=2069148&platform=Mac&Consent=0&channel=Stable"
        curl -L -o edge-apple.pkg "https://go.microsoft.com/fwlink/?linkid=2093504&platform=Mac&Consent=0&channel=Stable"
        pkgutil --expand-full edge-intel.pkg Edge-Intel/
        pkgutil --expand-full edge-apple.pkg Edge-Apple/

    - name: Zip Edge.app
      if: steps.check-versions.outputs.version_changed == 'true'
      run: |
        ditto -c -k --sequesterRsrc --keepParent "Edge-Intel/MicrosoftEdge-${{ env.VERSION_EDGE }}.pkg/Payload/Microsoft Edge.app" ./MicrosoftEdge-Intel.zip
        ditto -c -k --sequesterRsrc --keepParent "Edge-Apple/MicrosoftEdge-${{ env.VERSION_EDGE }}.pkg/Payload/Microsoft Edge.app" ./MicrosoftEdge-Apple.zip

    - name: Create Release and Upload Assets
      if: steps.check-versions.outputs.version_changed == 'true'
      uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # pin@v1.12.0
      with:
        artifacts: "MicrosoftEdge-Intel.zip,MicrosoftEdge-Apple.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.VERSION_EDGE }}
        name: ${{ env.VERSION_EDGE }}

    - name: Commit and push if versions have changed
      if: steps.check-versions.outputs.version_changed == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add previous_version
        git commit -m "Update Edge versions to: ${VERSION_EDGE}"
        git push origin versions
